### ISSUE TITLE
Playground is not working properly.

### ISSUE THREAD

**Issue by ErKeLost** [Tresjs/playground#4]
I like your library very much and want to learn and use it in the website I'm about to create.

When I tried to check the playground demo, I found that it didn't display properly.
node version > 18
Steps 1： pnpm install
Steps 2： pnpm dev
My local implementation localhost：3000

![image](https://user-images.githubusercontent.com/66500121/221214293-9a08b1c2-44fe-4fd0-9b6e-eb021694964f.png)

https://playground.tresjs.org/vue/portal-journey/

![image](https://user-images.githubusercontent.com/66500121/221214416-e0bd7e18-304c-4347-8d15-69c92e3eead0.png)

Excuse me, which step did I do wrong?

**Comment by alvarosabu** [comment]
Hi there, thanks for reporting this issue. 

The error only happens with that experiment or the rest are also broken?

**Comment by ErKeLost** [comment]
The previous ones can be displayed normally, and some of them don't work properly.

The red arrow means it doesn't work properly. The yellow arrow can work.

![image](https://user-images.githubusercontent.com/66500121/221325013-8a011573-610b-4e07-bd77-c2a9be778403.png)

**Comment by ErKeLost** [comment]
I like your library very much. I'd like to ask how I can participate in the development and contribute.

**Comment by alvarosabu** [comment]
@ErKeLost thanks ☺️. Could you use this command on your local environment where you are trying to run the playground? 

```
npx envinfo --system --npmPackages '{vite,@tresjs/*, three, vue}' --binaries --browsers
```

**Comment by alvarosabu** [comment]
@ErKeLost please try again with the new playground, is using nuxt. If it doesn't work for you please re-open the issue
