### ISSUE TITLE
Good morning everynyan. How to change background to transparent

### ISSUE THREAD

**Issue by Tonight11** [Tresjs/playground#81]
So there is my code. And my canvas has black background and i wanna change it to transparent but it doesnt work. PLS HELP😿

<script setup>
  import { TresCanvas } from "@tresjs/core";
  import { OrbitControls, useFBX } from "@tresjs/cientos";

  const path = "/src/assets/model/room.fbx";
  const scene = await useFBX(path);
  console.log(scene);
</script>

<template>
  <TresCanvas>
    <TresPerspectiveCamera :position="[3, 2, 5]" />
    <OrbitControls />
    <Suspense>
      <primitive v-if="scene" :object="scene" scale="0.025" />
    </Suspense>
    <TresDirectionalLight :intensity="2" :position="[3, 3, 3]" />
    <TresAmbientLight :intensity="1" />
  </TresCanvas>
</template>

**Comment by WangShuan** [comment]
@Tonight11 Hi, you might want to try the following:
```
<TresCanvas :clear-color="false" alpha window-size>
```
1. Set clear-color to false.
2. Add alpha to the TresCanvas tag.

This approach seems feasible, but I'm not entirely certain if it is correct.

**Comment by WangShuan** [comment]
@Tonight11 Hi, 
I noticed there's no template code provided, but if you're looking to make the background of TresCanvas transparent, you can try the following:
```
<TresCanvas :clear-color="false" alpha window-size>
```

1. Set clear-color to false.
2. Add alpha to the TresCanvas tag.

This approach seems feasible, but I'm not entirely certain if it is correct.
Hope this helps! 😊
